FROM golang:1.17.1 as builder
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
	GOPROXY="https://goproxy.cn,direct"
WORKDIR /usr/app/
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY pkg pkg
COPY cmd cmd

RUN go build -o server ./cmd/server.go

FROM  alpine:latest

ENV TIME_ZONE  Asia/Shanghai
ENV serverAddr 0.0.0.0:8080

WORKDIR  /usr/app/
COPY  --from=builder /usr/app/server  .
CMD  ["/usr/app/server"]

